[evidence]
site_url = "https://asridhar29.github.io/lab-homepage/"
archive_url = https://web.archive.org/web/20260917052233/https://asridhar29.github.io/lab-homepage/
backlink_urls = [
  "https://christopherkirch.github.io/lab-homepage2/",
  "https://shelbyjayn.github.io/lab-homepage/"
]